### ISSUE TITLE
1.19.2- Client Testing Dyed Blocks Show Blank and/or Deep Desaturation When Placed In World

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PlatinPython/RGBBlocks#5] opened 2022-11-08 12:34 UTC
**Version Info**
- Minecraft: 1.19.2 forge 43.1.47
- RGB Blocks: RGB Blocks-1.19.2-1.1.6.1
- Rubidium Plus + Addons

**Description of the Bug**

- I dyed a block but when I place it the color does not show.

**Steps to Reproduce**

- Grab the above and dye and place a block.

**Screenshots**

![2022-11-08_06 30 09](https://user-images.githubusercontent.com/10351221/200564811-287961d4-f241-43a5-8fc0-ac7a1aba4adc.png)

**Comment by P3rf3ctXZer0** [comment] 2022-11-08 12:38
Might be a strange saturation issue. Check this out. 
![2022-11-08_06 36 38](https://user-images.githubusercontent.com/10351221/200565562-5bcfa6d6-64b1-45e2-a034-e113d3f6350c.png)
![2022-11-08_06 37 39](https://user-images.githubusercontent.com/10351221/200565568-24091386-eec2-44d8-9249-64983e6781dd.png)

**Comment by PlatinPython** [comment] 2022-11-08 23:09
This issue seems to be caused by rubidium extra and how biome blending is implemented in that mod.
Disabling biome blending or removing said mod seems to fix the issue.
So this bug must be fixed by rubidium extra and there's nothing I can do, so please report it to them.

**Closed as not planned by PlatinPython** 2022-11-08 23:09 UTC
Labels: bug, wontfix, other mod
